name: Build Scala JAR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt

      - name: Install SBT
        run: |
          SBT_VERSION="1.10.11"
          echo "Downloading SBT launcher v${SBT_VERSION}..."
          curl -sL "https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz" -o sbt.tgz
          tar xf sbt.tgz -C /opt/
          echo "/opt/sbt/bin" >> $GITHUB_PATH
          export PATH="/opt/sbt/bin:$PATH"
          echo "Verifying SBT installation..."
          sbt sbtVersion
          echo "SBT installation complete."

      - name: Debug - List Files and Directories
        run: |
          echo "Listing contents of repository root and 'resources/' folder:"
          ls -R .
          echo "--- Contents of resources/ ---"
          ls -l resources/
          echo "--- End Debug Listing ---"

      - name: Build Scala JAR with SBT Assembly
        # The JAR will be created in the `resources/` directory as per your `build.sbt`.
        # The output logs of this step will show the path where the JAR is generated.
        run: |
          echo "Starting SBT build process..."
          sbt clean assembly
          echo "SBT build process finished. Check the logs above for the exact JAR output path (e.g., in the 'resources/' directory)."

      # --- NEW STEP: Upload JAR as an Artifact ---
      - name: Upload JAR as Workflow Artifact
        uses: actions/upload-artifact@v4 # Uses the action to upload build artifacts
        with:
          name: structured-streaming-mq-jar # The name for your artifact (e.g., 'my-app-jar')
          path: resources/structured-streaming-mq-assembly-0.1.0-SNAPSHOT.jar # The exact path to the built JAR on the runner
          retention-days: 7 # Optional: How long to keep the artifact (default is 90 days)
      # --- END NEW STEP ---