name: Build Scala JAR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy-jar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: sbt

      # === NEW STEP: Install SBT ===
      - name: Install SBT
        run: |
          # Download the SBT launcher script
          SBT_VERSION="1.10.11"
          curl -sL "https://github.com/sbt/sbt/releases/download/v${SBT_VERSION}/sbt-${SBT_VERSION}.tgz" -o sbt.tgz
          tar xf sbt.tgz -C /opt/
          
          # Add the SBT bin directory to the PATH for current and subsequent steps
          echo "/opt/sbt/bin" >> $GITHUB_PATH
          export PATH="/opt/sbt/bin:$PATH"

          # Verify SBT installation
          sbt sbtVersion
          echo "SBT installation complete."
      # === END NEW STEP ===

      - name: Build Scala JAR with SBT Assembly
        run: sbt clean assembly

      - name: Locate Generated JAR file
        id: locate_jar
        run: |
          PROJECT_NAME="structured-streaming-mq"
          PROJECT_VERSION="0.1.0-SNAPSHOT"
          JAR_FILENAME="${PROJECT_NAME}-assembly-${PROJECT_VERSION}.jar"
          JAR_PATH=$(find ./resource/ -name "${JAR_FILENAME}" -print -quit)
          if [ -z "$JAR_PATH" ]; then
            echo "Error: No JAR file found in ./resource/ directory matching '${JAR_FILENAME}'."
            echo "Please verify your build.sbt assembly configuration and that the JAR is created in the 'resource/' folder."
            exit 1
          fi
          echo "Found JAR at: $JAR_PATH"
          echo "JAR_PATH=$JAR_PATH" >> $GITHUB_OUTPUT
          echo "JAR_FILENAME=$(basename $JAR_PATH)" >> $GITHUB_OUTPUT